module2-task1
htmlacademy-javascript/1990863-kekstagram-27 pull request #2
Opened 2022-10-03 18:35 UTC by ilianameit

ДЗ по функциям

2022-10-04 19:35 UTC, KletskovG requested changes

2022-10-04 19:35 UTC, KletskovG commented on js/main.js
> +function checkLenght(testString, maxLenght) {
Тут опечатка - checkLength должно быть

И можно сразу возвращать логическое выражение

```
function checkLength(testString, maxLength) {
return testString.length <= maxLength;
}
```

2022-10-04 19:35 UTC, KletskovG commented on js/main.js
> +function checkLenght(testString, maxLenght) {
Тут нужно убрать console.log, чтобы eslint не ругался и можно было влить ПР, можно просто в этом же файле по 1 разу вызвать эти функции и все 

И там нужно лишние пустые строки удалить, чтобы eslint не ругался

2022-10-04 19:35 UTC, KletskovG commented on js/main.js
> +  return 'NaN';
Должно быть просто NaN, иначе сейчас это строка

2022-10-05 18:13 UTC, ilianameit reviewed
.

2022-10-05 18:17 UTC, ilianameit commented
Не совсем поняла почему оно не обновилось при публикации...

2022-10-07 10:19 UTC, merged